services:
  ms-users:
    build: ./ms-users-challenge
    ports:
      - "8082:8082"
  ms-accounting-transactions:
    build: ./ms-accounting-transactions-challenge
    ports:
      - "8084:8084"
  myoracle:
    image: gvenzl/oracle-free
    ports:
      - "1521:1521"
    environment:
      - ORACLE_DATABASE=devlocal
      - APP_USER=develop
      - APP_USER_PASSWORD=adminroot
      - ORACLE_PASSWORD=adminroot
    volumes:
      - myoracle-data:/opt/oracle/oradata
volumes:
  myoracle-data:  
