CREATE TABLE "DEVELOP"."ACCOUNTS" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"ACCOUNT_NUMBER" NUMBER(19,0), 
	"AVAILABLE_BALANCE" NUMBER(19,0), 
	"CLIENT_ID" NUMBER(19,0), 
	"INITIAL_BALANCE" NUMBER(19,0), 
	"STATUS" NUMBER(1,0), 
	"TYPE" VARCHAR2(255 CHAR), 
	 CHECK (status in (0,1)) ENABLE, 
	 PRIMARY KEY ("ID")
     );
     
CREATE TABLE "DEVELOP"."CLIENTS" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"ADDRESS" VARCHAR2(255 CHAR), 
	"AGE" NUMBER(10,0), 
	"CLIENT_ID" VARCHAR2(255 CHAR), 
	"GENDER" VARCHAR2(255 CHAR), 
	"IDENTIFICATION_NUMBER" VARCHAR2(255 CHAR), 
	"NAME" VARCHAR2(255 CHAR), 
	"PASSWORD" VARCHAR2(255 CHAR), 
	"PHONE_NUMBER" VARCHAR2(255 CHAR), 
	"STATUS" NUMBER(1,0), 
	 CHECK (status in (0,1)) ENABLE, 
	 PRIMARY KEY ("ID")
     );
     
CREATE TABLE "DEVELOP"."MOVEMENTS" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"ACCOUNT_ID" NUMBER(19,0), 
	"MOVEMENT_DATE" TIMESTAMP (6), 
	"NEW_BALANCE" NUMBER(19,0), 
	"TYPE" VARCHAR2(255 CHAR), 
	"VALUE" NUMBER(19,0), 
	 PRIMARY KEY ("ID")
     );
     